# preload = /home/dima/proj/desktop-setup/wallpaper/F42-01-day.jpg
# wallpaper = , /home/dima/proj/desktop-setup/wallpaper/F42-01-day.jpg
splash = false

wallpaper {
    monitor = 
    # path = /home/dima/proj/desktop-setup/wallpaper/F42-01-day.jpg
    path = /home/dima/proj/desktop-setup/wallpaper/hyprland-wallpapers.png
    fit_mode = cover
}
