modmap:
  #- name: Global
  #  remap:
  #    KEY_LEFTALT: KEY_LEFTCTRL
  #    KEY_LEFTCTRL: KEY_LEFTMETA
  #    KEY_LEFTMETA: KEY_LEFTALT

  - name: "Built In Keyboard"
    device:
      only: "AT Translated Set 2 keyboard"
    remap:
      KEY_LEFTALT: KEY_LEFTCTRL
      KEY_LEFTCTRL: KEY_LEFTMETA
      KEY_LEFTMETA: KEY_LEFTALT

  - name: "KINESIS"
    device:
      only: "KINESIS CORPORATION KB800HM Kinesis Freestyle2 for Mac"
    remap:
      KEY_LEFTMETA: KEY_LEFTCTRL
      KEY_LEFTCTRL: KEY_LEFTMETA
#      KEY_LEFTMETA: KEY_LEFTALT
